server:
  port: 8080

spring:

  application:
    name: rest-api

  datasource:

    url: jdbc:h2:file:./data/rest_api;AUTO_SERVER=TRUE
    username: rest_user
    password: password
    driver-class-name: org.h2.Driver

  jpa:

    hibernate.ddl-auto: create-drop
    #jpa.hibernate.ddl-auto=update
    properties.hibernate.format_sql: true
    show-sql: true

jwtSecret: 2f98aa94ac29242baf941c383a0c9b4b1ef942bea088a47429f5d2958618182d